# -*- coding: utf-8 -*-
"""Three last edits to the gate, and one new check.

  1. chapter 09's own contents figures were the only pair the cheat-sheet pack
     does not carry, so they were still the v16 cost to open and exit value;
  2. the occupancy check's approved context for the sensitivities table held a
     literal return, so it went stale with the model. It derives now;
  3. the written hotel pages read a comparable against the subject, and the
     subject column is the underwrite's own figure. That pack is regenerated by
     another pipeline, which puts back whatever its sources hold, so a check
     names the retired figures and names the script that re-strikes them.

    python tools/patch-verify-hotelpages.py
"""
import json, os, pathlib

HERE = pathlib.Path(__file__).resolve().parent.parent
DEAL = pathlib.Path(os.environ.get(
    "FAWLEY_DEAL_ROOT",
    r"D:\OneDrive - Strand Labs\2. Clients\Align\2. Live Deals\Fawley Court"))
V = HERE / "verify.mjs"
IDX = HERE / "index.html"
REC = json.loads((DEAL / "Model" / "docs" / "v29-figures.json").read_text(encoding="utf-8"))
F = REC["fig"]

CHECK = r'''
/* the written hotel pages read a comparable against the subject, and the
   subject column is the underwrite's own figure. That pack is built by its own
   pipeline and regenerated from its own sources, so a re-strike of the model
   has to reach it too. */
for (const [slug, rec] of Object.entries(hpSource)) {
  for (const row of rec.against || []) {
    if (!row || row.length < 3 || typeof row[2] !== "string") continue;
    checked++;
    const stale = RETIRED.find(t => row[2].includes(t)
      || row[2].includes(t.replace("£", "GBP ")) || row[2].includes(t.replace("£", "GBP")));
    if (stale && !liveFigures.has(stale))
      fail(`HOTEL PAGE SUBJECT CELL IS STALE  ${slug}/${row[0]}`,
        `"${row[2]}" carries ${stale} — run python tools/restrike-hotelpages.py, then tools/inline-hotelpages.py`);
  }
}
'''


def main():
    s = V.read_text(encoding="utf-8")

    # the occupancy context, derived rather than typed
    old = '  "0.65 \\u2192 12.99%",                        // the sensitivities table\'s underwritten cell'
    assert old in s, "occupancy context not found"
    s = s.replace(old,
                  '  "0.65 \\u2192 " + modelSrc.fig.irr,      // the sensitivities table\'s underwritten cell',
                  1)
    print("  ok  the occupancy context follows the model")

    # the new hotel-page check, after the retired-figure block
    anchor = '/* ══ house rules'
    assert anchor in s
    s = s.replace(anchor, CHECK.strip("\n") + "\n\n" + anchor, 1)
    print("  ok  hotel-page subject cells checked against the retired list")
    V.write_text(s, encoding="utf-8")

    h = IDX.read_text(encoding="utf-8")
    old_fig = 'figures: [["£194.2m","Cost to open"],["£248.0m","Exit value"]]'
    new_fig = f'figures: [["{F["cost_to_open"]}","Cost to open"],["{F["exit_value"]}","Exit value"]]'
    assert h.count(old_fig) == 1, "chapter 09 figures not found"
    h = h.replace(old_fig, new_fig)
    IDX.write_text(h, encoding="utf-8")
    print("  ok  chapter 09's contents figures re-struck")


if __name__ == "__main__":
    main()
