# -*- coding: utf-8 -*-
"""Re-strike the portal's authored chapters onto the current model.

The six data blocks are regenerated by `build-blocks.py`. This carries the
prose: chapters 01, 04, 06 and 07 are rewritten whole, because their tables
describe a scheme that changed rather than figures that moved, and chapters 02,
03 and 08 and the case plates take named replacements.

Every replacement asserts its own count, so a source line that has moved on
stops the run rather than being silently skipped.

    python tools/restrike-chapters.py
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEAL = os.environ.get(
    "FAWLEY_DEAL_ROOT",
    r"D:\OneDrive - Strand Labs\2. Clients\Align\2. Live Deals\Fawley Court")
IDX = os.path.join(HERE, "index.html")
REC = json.load(open(os.path.join(DEAL, "Model", "docs", "v29-figures.json"), encoding="utf-8"))

F = REC["fig"]
S = REC["sens"]
LAD = {int(r["price"] / 1e6): r for r in REC["ladder"]}
RUNG = {int(r["price"] / 1e6): r for r in REC["rungs"]}
BS = REC["backsolve"]
CASE = REC["cases"]
FLOW = REC["flows"]
FT = REC["flow_totals"]
D = REC["derived"]
X = REC["extra"]

MODEL_NAME = "Financial Model v29"
SAVED = "19 August 2026"
NDASH, MDASH, ARROW = "\u2013", "\u2014", "\u2192"


def p2(k):
    return f"{S[k]['irr']*100:.2f}%"


def m1(v):
    return f"£{v/1e6:.1f}m"


def m2(v):
    return f"£{v/1e6:.2f}m"


def case(k, field, fmt=m1):
    return fmt(CASE[k][field])


def rung(p, lever):
    r = RUNG[p][lever]["solved"]
    return {"adr": f"£{r:,.0f}", "exit_yield": f"{r*100:.2f}%", "resi_psf": f"£{r:,.0f}"}[lever]


def neg(v):
    """A negative percentage as the page prints it."""
    return f"({abs(v)*100:.2f})%" if v < 0 else f"{v*100:.2f}%"


# ══ chapter 01 ════════════════════════════════════════════════════════
CH01 = f'''{{
  id: "summary", num: "01", eyebrow: "Summary", title: "Executive Summary",
  blurb: "The scheme, the consent position, the underwrite and what it returns at the ruled price.",
  figures: [["{F['entry']}","Ruled entry"],["{F['irr']} / {F['em']}","Levered IRR \u00b7 multiple"]],
  views: [
  {{ id: "", title: "Executive Summary", kicker: "Summary",
    figure: "{F['irr']} / {F['em']} at {F['entry']}", blurb: "",
    lead: [
      ["kpis",[["{F['irr']}","Levered IRR at the ruled price"],["{F['em']}","Equity multiple"],["{F['peak_equity']}","Peak equity"],["c.\u00a370m","Agent guidance, understood","q"]]],
      ["tbl",{{"cls":"labeled","rows":[
        [null,["Asset and scheme","A Grade I house of 1684 in a Grade II* registered park on the Thames above Henley, freehold. The scheme is a 60-key hotel {MDASH} 17 Main House, 43 Stables and Courtyard {MDASH} with 12 branded residences sold on 999-year leaseholds"]],
        [null,["Consent position","Both consents were granted on 6 December 2024 and both run to 6 December 2027. The full permission, 23/07589/FUL, consents 15 courtyard guest suites tied by condition to the estate\u2019s existing retreat and conference use, and the applicant told the council in writing that no change of use was proposed. The underwrite puts 43 keys in those courtyards and trades them as a flagged hotel, so both the use and the quantum need a permission that has never been applied for. Nothing is discharged, five conditions are pre-commencement, and no residential application exists"]],
        [null,["The underwrite","ADR {F['adr_y1']} in year-1 money, occupancy 60{NDASH}70%, hotel works {F['capex_hotel']} = {F['capex_hotel_per_key']} a key from a 162-line ground-up budget, exit {F['exit_yield']}, twelve residences"]],
        [null,["What it returns","{F['irr']} and {F['em']} at the ruled {F['entry']} price, on {F['peak_equity']} of peak equity, {F['cost_to_open']} of cost to open and {F['levered_profit']} of levered profit. Year-7 net operating income is {F['yield_on_cost']} of the cost to open, a spread of {F['dev_spread_bp']} over the exit yield"]],
        [null,["The price","{F['entry']} is the price Align has ruled, and returns are outputs at it. Agent guidance is understood at about \u00a370m. On these dials a 13% return solves at {BS['0.13']['fig']} {MDASH} {D['bar_gap']} above the ruled price {MDASH} 14% at {BS['0.14']['fig']} and 15% at {BS['0.15']['fig']}"]],
        [null,["Entry ladder","Each rung above the ruled price is priced by what one input must reach to hold 13.00%: at \u00a360m a {rung(60,'adr')} rate, a {rung(60,'exit_yield')} exit or {rung(60,'resi_psf')}/sqft residences; at \u00a370m, {rung(70,'adr')}, {rung(70,'exit_yield')} and {rung(70,'resi_psf')}"]],
        [null,["Rate assumption","{F['adr_y1']} sits a third above the highest UK lead-in held and below the four cohort lead-ins of \u00a31,372 and above. No UK evidence supports it"]],
        [null,["What four operators say","Six Senses, Belmond, Rocco Forte and CBRE have each forecast this asset. On rooms revenue a key they agree with the underwrite within 2%. On everything else they do not: total revenue a key is 1.74 times their average, food and beverage 2.93 times, spa 3.55 times, and none of the four carries a membership line. The equity return sits in engines no operator who has seen this building models"]],
        [null,["The evidence","European ceiling cohort for rate and capital cost; the UK set for occupancy, margin and payroll; ten case studies with their estimated P&amp;Ls; four operator forecasts for this asset. The room holds no trading record, and it holds no cost plan either {MDASH} the capital cost is built line by line in chapter 05"]]]}}],
    ],
    reason: [
      ["src","Source: Align model, {MODEL_NAME}, saved state {SAVED}; every solved figure measured on scratch copies of it on the same day. Every page that follows carries the basis, window and source of its figures. Occupancy is an interval of 60{NDASH}70% in narrative; {F['occ_stab']} is the model input. The operator\u2019s base and incentive fees sit inside the profit and loss account, so the net operating income and the margin on it are after them. The exit is modelled as a sale of the holding company\u2019s shares, so no capital gain arises in the vehicle; the sensitivities measure the asset-sale case. The consent position comes from the public planning register, retrieved 18 August 2026. The printed memorandum remains on the earlier v15 basis and this portal supersedes it."],
    ] }}
  ]
}},'''


# ══ chapter 04 ════════════════════════════════════════════════════════
def ch04():
    def cell(v):
        """A repayment prints in brackets and in the negative colour."""
        return "<span class='neg'>" + v + "</span>" if v.startswith("(") else v

    rows = "\n        ".join(
        '[null,["%s","%s","%s","%s","%s"]],'
        % (r["period"], r["equity_in"], r["distributed"], cell(r["senior"]), cell(r["refi"]))
        for r in FLOW)
    margin_rows = "".join(
        ('["subject",["' + m["index"] + f' {MDASH} underwritten","<span class=\'emph\'>' + m["gop_margin"]
         + "</span>\",\"<span class='emph'>" + m["irr"] + '</span>"]],')
        if m["index"] == F["staff_index"] else
        ('[null,["' + m["index"] + '","' + m["gop_margin"] + '","' + m["irr"] + '"]],')
        for m in REC["margin"])
    return f'''{{
  id: "underwrite", num: "04", eyebrow: "The Underwrite", title: "The Underwrite",
  blurb: "The dial set, the revenue engines, the margin frame, the capital stack and the residences.",
  figures: [["{F['rev_y7']}","Year-7 revenue"],["{F['gop_margin_y7']}","Year-7 GOP margin"]],
  views: [
  {{ id: "", title: "The Dials", kicker: "Underwrite",
    figure: "Seventeen dials at the ruled price", blurb: "",
    lead: [
      ["dials16"],
    ],
    reason: [
      ["src", DIAL_SRC],
    ] }},
  {{ id: "dial-set", title: "The Dial Set", kicker: "Underwrite",
    figure: "Ten dials, with basis", blurb: "Every dial, whether it is a market or a decision input, and the note that governs it.",
    lead: [
      ["tbl",{{"cls":"num wide","head":["Dial","Underwritten",{{"t":"Basis","a":"c"}},"Note"],"rows":[
        [null,["Keys","60, courtyard 12","Decision","The vendor\u2019s own scheduled scheme: 17 Main House, 43 Stables and Courtyard, the courtyard opening first. The consented courtyard count is 15, and 60 keys is now the consensus across three of the four operator forecasts"]],
        [null,["ADR","{F['adr_y1']} {ARROW} {F['adr_y7']}","Decision","Below the four cohort lead-ins of \u00a31,372 and above; a third over the top UK median. The four operator forecasts average \u00a31,183 at their own stabilised year"]],
        [null,["Occupancy","{F['occ_stab']} [0.60{NDASH}0.70]","Decision","Reached in trading year 7. The four operator forecasts average 65.5%, which is where the model already sits"]],
        [null,["Cost of works","{F['capex_works_total']} {MDASH} {F['capex_hotel']} hotel, {F['capex_resi']} residences","Decision","A 162-line ground-up budget priced after the site inspection of 17 August 2026: a quantity and a rate on every line, then {F['capex_prelims_pct']} preliminaries, {F['capex_fees_pct']} fees and {F['capex_cont_pct']} contingency on the hotel limb, which are Rocco Forte\u2019s own loadings. Chapter 05 carries every line and its basis"]],
        [null,["Staff cost index","{F['staff_index']}","Decision","All seven direct-wage lines; undistributed costs are not scaled. Per key the model spends more on undistributed expenses than all four operator forecasts"]],
        [null,["Residences","12 at {F['resi_psf']}/sqft","Market","{F['resi_sqft']} sqft average, the vendor\u2019s advised product; prices escalate {F['resi_esc']} a year to each sale quarter; absorption {F['resi_absorption']} a year, on 999-year leaseholds ruled 18 August 2026. The rate sits above the \u00a31,100 cap the underwrite previously ruled and above the \u00a31,250 it named as upside, and it has not yet been given its own evidence basis {MDASH} an open item"]],
        [null,["Fees","{F['fee_op_base']} / {F['fee_incentive']} / 1.5%","Decision","Operator base on total revenue and incentive on GOP, both charged inside the profit and loss account, with brand charges on rooms. Align funds no equity and earns the {F['fee_am']} escalating AM fee and a promote over {F['promote_h1']} / {F['promote_h2']} / {F['promote_h3']} hurdles carried at nil, so returns are pre-promote"]],
        [null,["Debt","{F['fin_senior_ltc']} LTC senior; refinancing at Q{F['fin_refi_q']}","Decision","Senior at base {F['base_rate']} plus {F['fin_senior_margin']}, PIK {F['fin_pik_q']} quarters. The refinancing is sized to the lower of {F['fin_refi_ltv']} LTV at a {F['fin_refi_yield']} yield and {F['refi_min_icr']} post-fee cover, margin {F['fin_refi_margin']}; the cover test binds, drawing {F['refi_draw']} against the {F['senior_peak']} of senior it repays"]],
        [null,["Exit","{F['exit_yield']}","Decision","On adjusted NOI with {F['purch_costs_pct']} purchasers\u2019 costs; hotel alone"]],
        [null,["Programme, hold","{F['capex_prog_q']} quarters, {F['hold_yrs']} years","Decision","Opening at T+3.5; the single-lever sensitivities move it"]]]}}],
    ],
    reason: [
      ["src","Source: Align model, {MODEL_NAME} at the ruled {F['entry']} price. Market means comp-anchored judgment; Decision a ruling that diligence refines. Operator comparisons are the four forecasts on the Brands tab of the model: Six Senses (IHG) March 2025, Belmond June 2025, Rocco Forte June 2026 and CBRE\u2019s cashflow from the vendor\u2019s information memorandum. Corporation tax runs at {F['tax_corp']}; the exit is a share sale, and the asset-sale alternative is measured in the sensitivities."],
    ] }},
  {{ id: "engines", title: "Revenue Engines", kicker: "Revenue",
    figure: "{F['rev_y7']} in year 7", blurb: "The five demand engines and the year-7 revenue mix.",
    lead: [
      ["tbl",{{"cls":"num wide","head":["Engine","Underwritten, Y1 money",{{"t":"Year 7","a":"r"}},{{"t":"Share","a":"r"}},"Boundary"],"rows":[
        [null,["Regatta hospitality","{F['regatta_days']} days \u00d7 {F['regatta_covers']} covers \u00d7 {F['regatta_spend']} a head","{F['hire_rev_y7']}","{MDASH}","The vendor\u2019s own six-day format; runs from year 1, through the works"]],
        [null,["Exclusive-use buyouts","{F['buyouts_y7']} a year at a {F['buyout_premium']} premium over accommodation","{MDASH}","{MDASH}","The premium has no filed comparable anywhere in the evidence estate. Turning the buyouts off costs {abs(S['buyouts_off']['d_pp']):.2f}pp"]],
        [null,["Corporate events","{F['corp_y7']} a year at {F['corp_rev_y1']}","{MDASH}","{MDASH}","Subject prices exclude rooms"]],
        [null,["Day meetings and private dining","{F['hires_per_day']} hires a day at {F['hire_rate']}, twelve delegates","{MDASH}","{MDASH}","Against Beaverbrook\u2019s filed room hire of \u00a3491,623 on 56 keys. Off, it costs {abs(S['daymeetings_off']['d_pp']):.2f}pp"]],
        [null,["The members\u2019 club","{F['members']} members at {F['member_fee']} a month, {F['founder_cap']} founders at {F['founder_fee']}","{F['mem_rev_y7']}","{MDASH}","No filed comparable for the fee. Off, it costs {abs(S['club_off']['d_pp']):.2f}pp {MDASH} the largest revenue lever in the model"]],
        ["divider",["Year-7 revenue mix"]],
        [null,["Rooms","60 keys at {F['adr_y7']}, occupancy {F['occ_stab']}","{F['rooms_rev_y7']}","{F['rooms_share_y7']}","RevPAR {F['revpar_y7']}, year-7 money"]],
        [null,["Food and beverage","Restaurants, bar, tea, events, Regatta, the River Club","{F['fb_rev_y7']}","{F['fb_share_y7']}","2.93 times the four operator forecasts per key"]],
        [null,["Spa, club, other","Spa, memberships, hire, other","{F['other_rev_y7']}","{F['other_share_y7']}","Partly a members\u2019-club case, stated as one"]],
        ["total",["Total revenue","Year 7, stabilised","<span class='emph'>{F['rev_y7']}</span>","100%","{F['rev_per_key_y7']} a key; the four operator forecasts average \u00a3450,300"]],
        [null,["GOP and NOI","NOI after the operator\u2019s fees","{F['gop_y7']} / {F['noi_y7']}","{F['gop_margin_y7']} / {F['noi_margin_y7']}","The base and incentive fees are charged inside the P&amp;L, so this NOI is after them; only Align\u2019s own {F['fee_am']} fee sits below it"]]]}}],
    ],
    reason: [
      ["src","Source: Align model, {MODEL_NAME}. Engine sensitivities measured on scratch copies {SAVED}, each switch moved alone with the state restored afterwards. Operator comparisons from the Brands tab: four independent forecasts for this asset, none of which carries a membership line. Drivers above the divider are year-1 money and the year-7 column carries the escalation chain, so the two do not multiply out. Engine defaults are blessed assumptions replaced by vendor actuals at diligence; nothing in the data room prices them, and the club fee and the buyout premium are the two weakest numbers in the underwrite."],
    ] }},
  {{ id: "margin", title: "The Margin Frame", kicker: "Margin",
    figure: "{F['gop_margin_y7']} at index {F['staff_index']}", blurb: "The staff cost index against the GOP margin and the levered return it produces.",
    lead: [
      ["panes",{{"split":"46fr 54fr","left":{{"h":"The staff cost index, and what each setting returns","b":[["tbl",{{"cls":"num","head":["Staff cost index",{{"t":"Year-7 GOP margin","a":"r"}},{{"t":"Levered IRR at the price","a":"r"}}],"rows":[{margin_rows}],"note":"The evidence beside runs 25.8% at Smeralda to 36.5% at Messardi\u00e8re, with Belmond\u2019s audited segment at 33{NDASH}35% and Le Grand Contr\u00f4le negative. The four operator forecasts for this asset average a 32.6% GOP margin, which is inside a point and a half of the underwrite."}}]]}},"right":{{"h":"Where the margin sits against the evidence","b":[["tbl",{{"cls":"num","head":["Series",{{"t":"Margin","a":"r"}},"Basis"],"rows":[
        [null,["Villa d\u2019Este","41.2%","EBITDA, FY2025 filed; the outer bound"]],
        [null,["Rocco Forte, for this asset","37.7%","GOP, their own year-5 forecast, June 2026"]],
        [null,["Messardi\u00e8re","36.5%","EBITDA, FY2024, ~5.5-month season"]],
        ["key",["Align corpus p75","36.0%","GOP, 67 hotels, FY2012{NDASH}25A"]],
        ["subject",["Fawley Court {MDASH} underwritten","<span class='emph'>{F['gop_margin_y7']}</span>","GOP, year 7, Align model"]],
        [null,["Belmond Europe","33{NDASH}35%","Adjusted EBITDA, FY2016{NDASH}18, audited"]],
        [null,["Six Senses, for this asset","32.9%","GOP, their own year-5 forecast, March 2025"]],
        ["key",["Align corpus p50","31.1%","GOP, 67 hotels, FY2012{NDASH}25A"]],
        [null,["Careys Manor","~30%","GOP, FY2023A; the highest UK country-house actual held"]],
        [null,["Wellness resorts","26%","GOP, HotStats segment print, 2025"]],
        [null,["Smeralda portfolio","25.8%","EBITDA, FY2024, four hotels"]]]}}]]}}}}],
    ],
    reason: [
      ["para","The staff cost index is the margin lever. The table shows the year-7 GOP margin and the levered IRR at each setting, against the evidence range beside it. The margin itself is not the outlier in this underwrite; the revenue it is struck on is."],
      ["src","Source: Align model, {MODEL_NAME} {MDASH} every cell in the index column measured on the model at the ruled price, {SAVED}; Align hotel database P&amp;L corpus \u2014 612 filed actual-basis periods, 67 hotels, FY2012{NDASH}FY2025 concentrated FY2017{NDASH}FY2023, each hotel entering at its own median; cohort operations pack; the Brands tab for the two operator forecasts shown. EBITDA and GOP are different lines; the comparison is one of order."],
    ] }},
  {{ id: "capital", title: "Capital &amp; Cost to Open", kicker: "Capital",
    figure: "{F['cost_to_open']} to open", blurb: "What it costs to open and to exit, how it is funded, and how the exit value is struck.",
    lead: [
      ["panes",{{"split":"50fr 50fr","left":{{"h":"Hotel cost to open and exit","b":[["tbl",{{"cls":"num","head":["Line",{{"t":"Amount","a":"r"}}],"rows":[
        [null,["Purchase price","{F['entry']}"]],
        [null,["Acquisition costs at {F['acq_costs_pct']}","{D['acq_costs_amount']}"]],
        [null,["Hotel works spent to opening","{F['co_capex']}"]],
        [null,["Arrangement fee","{F['co_arrfee']}"]],
        [null,["Capitalised interest, to opening","{F['co_interest']}"]],
        [null,["Pre-opening operating shortfall","{F['co_shortfall']}"]],
        ["total key",["Cost to open","<span class='emph'>{F['cost_to_open']}</span>"]],
        ["total key",["Hotel cost to exit","<span class='emph'>{F['all_in_to_exit']}</span>"]],
        [null,["Residential build, all in","{F['capex_resi']}"]],
        [null,["Residential sales fee, {F['resi_fee_pct']} of gross proceeds","{F['resi_sales_fee']}"]],
        ["total key",["Total project cost through exit","<span class='emph'>{D['total_project_cost']}</span>"]]]}}]]}},"right":{{"h":"How it is funded, and the exit","b":[["tbl",{{"cls":"num","head":["Line",{{"t":"Amount","a":"r"}}],"rows":[
        [null,["Equity drawn over the hold, which is also peak equity","{F['peak_equity']}"]],
        [null,["Senior drawn over the works, cumulative","{F['senior_drawn_total']}"]],
        [null,["Peak senior balance, at opening","{F['senior_peak']}"]],
        ["key",["Refinancing drawn at Q{F['fin_refi_q']}","<span class='emph'>{F['refi_draw']}</span>"]],
        [null,["Exit-year NOI, after the operator\u2019s fees","{F['exit_noi']}"]],
        [null,["Less Align\u2019s asset-management fee","<span class='neg'>({F['exit_am_fee']})</span>"]],
        ["subtotal",["Adjusted NOI at exit","{F['exit_adjnoi']}"]],
        [null,["Exit yield / purchasers\u2019 costs","{F['exit_yield']} / {F['purch_costs_pct']}"]],
        ["total key",["Exit value, hotel alone","<span class='emph'>{F['exit_value']}</span>"]],
        [null,["Per key \u00b7 unadjusted NOI on the gross value","{F['exit_per_key']} \u00b7 {F['exit_noi_on_gross']}"]]]}}]]}}}}],
    ],
    reason: [
      ["src","Source: Align model, {MODEL_NAME}. Cost to open, {F['cost_to_open_key']} a key, and hotel cost to exit are hotel-limb figures. The works line here is the {F['co_capex']} spent by the opening quarter; the hotel budget is {F['capex_hotel']} in total, and the balance spends on estate lines that run past the opening. Total project cost through exit adds the residential build to the hotel cost to exit; it is an arithmetic aggregation, and a sources-and-uses reconciliation is a diligence-stage exercise. The operator\u2019s base and incentive fees are charged inside the P&amp;L, so the exit deducts only Align\u2019s own escalated {F['exit_am_fee']} fee: {F['exit_adjnoi']} \u00f7 {F['exit_yield']} = {F['exit_gross']} gross, \u00f7 1.068 purchasers\u2019 costs = {F['exit_value']} net; the unadjusted {F['exit_noi']} on that gross is {F['exit_noi_on_gross']}. Cash is retained to fund later drawdowns, so no equity is called after the first distribution. The capital partner provides all the equity and Align funds none."],
    ] }},
  {{ id: "profile", title: "Drawdown &amp; Return Profile", kicker: "Capital",
    figure: "Peak equity {F['peak_equity']}", blurb: "Equity in, cash out, and the year the capital comes back.",
    lead: [
      ["wf","equity"],
      ["exhibit",{{"h":"Annual flows, \u00a3m","b":[["tbl",{{"cls":"num","head":["Period",{{"t":"Equity in","a":"r"}},{{"t":"Distributed","a":"r"}},{{"t":"Senior","a":"r"}},{{"t":"Refi","a":"r"}}],"rows":[{rows}
        ["total",["Drawn over the hold","<span class='emph'>{FT['equity_in']}</span>","{MDASH}","{FT['senior']}","{FT['refi']}"]],
        [null,["Returned over the hold","{MDASH}","{FT['distributed']}","<span class='neg'>{FT['senior_repaid']}</span>","<span class='neg'>{FT['refi_repaid']}</span>"]]]}}]]}}],
    ],
    reason: [
      ["bullets",["<b>Peak equity {F['peak_equity']}</b> at quarter 12, the end of year 3, and equal to the total drawn: cash funds later drawdowns, so nothing is called after the first distribution. That equality holds only at the {F['refi_min_icr']} cover test the refinancing is sized on.","<b>Capital comes back in year 8</b>: cumulative net equity is {D['cum_equity_y7']} at the end of year 7, and the {FLOW[8]['distributed']} distributed in year 8 clears it.","<b>The refinancing more than clears the senior</b> {MDASH} {F['refi_draw']} drawn against the {F['senior_peak']} balance it repays. The cover test that sizes it is set at {F['refi_min_icr']}, and a lender holding 1.30x reopens a capital call."]],
      ["src","Source: Align model, {MODEL_NAME}, quarterly rows aggregated to deal years at the ruled price, {SAVED}. Close is the Sep 2026 completion quarter; Y8 ends Sep 2034. Senior and refi totals are gross drawdowns and the bracketed entries repay those facilities, so nothing is netted between the rows. Annual cells round to \u00a30.1m against totals struck on unrounded quarterly rows, so a column can sum \u00a30.1m away from its total. The chart is this table netted, cumulative."],
    ] }},
  {{ id: "residences", title: "Residences {MDASH} the Adopted Product", kicker: "Residences",
    figure: "12 \u00d7 {F['resi_sqft']} sqft at {F['resi_psf']}", blurb: "The vendor's own advised product, and the price the model now takes it at.",
    lead: [
      ["exhibit",{{"h":"The underwrite against the vendor's own advice","b":[["tbl",{{"cls":"num","head":["Line",{{"t":"Underwritten","a":"r"}},"Savills, for Cherrilow, October 2025"],"rows":[
        [null,["Units","<span class='emph'>{F['resi_units']}</span>","A maximum of 12: five 5-bed Meadows houses, seven 6-bed river houses"]],
        [null,["Average GIA","{F['resi_sqft']} sqft","5,200 sqft for 5-beds, 5,700 for 6-beds"]],
        [null,["Price","<span class='emph'>{F['resi_psf']}/sqft</span>","\u00a31,934 weighted: \u00a31,450 Meadows, \u00a32,250 riverside"]],
        [null,["Price growth to sale","{F['resi_esc']} a year","Not addressed"]],
        [null,["Gross, escalated to each sale quarter","{F['resi_gross']}","GDV \u00a3127.475m at today\u2019s prices"]],
        [null,["Cost of the limb, all in","{F['capex_resi']}","{MDASH}"]],
        ["total",["Net to the deal","<span class='emph'>{F['resi_net']}</span>","{MDASH}"]],
        [null,["Absorption","{F['resi_absorption']} a year","3 to 4 a year over three years"]],
        [null,["Tenure","999-year leasehold","Savills assumes 999-year long leaseholds"]]],"note":"Savills schedules 65,900 sqft; the model\u2019s {F['resi_sqft']} sqft average gives {F['resi_total_sqft']} sqft, a difference of 100 sqft that is immaterial. Tenure was ruled at 999-year leasehold on 18 August 2026, following Savills\u2019 own assumption. The {F['resi_psf']} rate and the {F['resi_esc']} growth both sit above what the underwrite has ruled {MDASH} the rate above the \u00a31,100 cap and the \u00a31,250 named upside, the growth above the 2.5% general inflation the rest of the model runs on. Neither has been given its own evidence basis."}}]]}}],
    ],
    reason: [
      ["cards",[["What the local evidence prints","RG9 prime sold evidence gives a \u00a31,107 median and an upper quartile of \u00a31,478; the one branded scheme held, Lakes by Yoo, prints \u00a3886."],["What Savills says of its number","\u00a31,934/sqft is a 63% premium over the local top 5% at \u00a31,186, which Savills calls unprecedented."],["What the rate is worth","At \u00a31,100 the case returns {p2('resi_1100')} and at \u00a31,250 {p2('resi_1250')}, against {F['irr']} at the {F['resi_psf']} the model holds. The limb is worth about {abs(S['resi_1500']['d_pp'] - S['resi_1100']['d_pp']):.1f} points across that band."],["What has to be true","Residential consent in a Grade II* registered park, where no UK precedent was located, and where no application has ever been made {MDASH} and an evidence basis for {F['resi_psf']} that the underwrite has not yet ruled."]]],
      ["src","Source: Data Room 3.4.1 Savills Residential Feasibility Report for Cherrilow Ltd, 9 October 2025, read directly \u2014 pp. 5 and 51 for the schedule, sizing, GDV and absorption, p. 24 for the \u00a31,186/sqft local top-5% reference, pp. 7 and 47 for planning and tenure, pp. 2 and 58 for the non-valuation basis. Savills states the report is not a Red Book valuation, accepts no third-party reliance and restricts reproduction or quotation without consent; confirm permitted use before external circulation. Align model for the underwritten column."],
    ] }},
  {{ id: "residences-evidence", title: "Residences {MDASH} Sold Evidence", kicker: "Residences",
    figure: "RG9 median \u00a31,107", blurb: "What the sold-price register prints around the reach, and what it does not hold.",
    lead: [
      ["tbl",{{"cls":"num wide","head":["Evidence set",{{"t":"n","a":"r"}},{{"t":"Median \u00a3/sqft","a":"r"}},{{"t":"P25\u2013P75","a":"r"}},"Basis"],"rows":[
        ["subject",["Fawley Court {MDASH} underwritten","12","<span class='emph'>{F['resi_psf']}</span>","{MDASH}","{F['resi_sqft']} sqft average, escalating {F['resi_esc']} a year to each sale quarter; absorption {F['resi_absorption']} a year"]],
        [null,["Savills recommendation","12","\u00a31,934","\u00a31,450\u20132,250","Weighted across 12 units, October 2025; a 63% premium over the local top 5% at \u00a31,186/sqft"]],
        [null,["RG9 prime Henley reach","10","\u00a31,107","\u00a3804\u20131,478","Sold 2021\u201326, single dwellings, farm titles out"]],
        [null,["The Lakes by Yoo","17","\u00a3886","\u00a3744\u2013959","One estate-branded development; the cleanest analogue"]],
        [null,["St George\u2019s Hill, Weybridge","12","\u00a3797","\u00a3655\u20131,255","Sold at \u00a34m and above; the Wentworth Estate prints \u00a3794 on the same convention"]],
        [null,["Castello di Reschio {MDASH} absorption","31","Not computable","","31 of about 50 farmhouse ruins restored and sold freehold at about \u20ac10m each; no dated series"]],
        [null,["Field Place, Remenham Hill","2","\u00a31,526 {ARROW} \u00a31,755","{MDASH}","The highest print in the immediate reach: a repeat sale, Jan 2022 then Aug 2023, same EPC area, up 15%. Greycroft printed \u00a31,589 and Hill House \u00a31,334, both in Fawley"]],
        ["total",["The limb, net","12","<span class='emph'>{F['resi_net']}</span>","{MDASH}","Gross {F['resi_gross']} escalated, less a {F['resi_fee_pct']} sales fee and {F['capex_resi']} of all-in cost; the cost is itemised in chapter 05"]]],"note":"The sold-price register returned no branded-residence comparables, and the one UK scheme with resale activity, Hamilton Grand, is in Scotland and outside it. Absorption of {F['resi_absorption']} a year is a judgment input inside Savills\u2019 3 to 4."}}],
    ],
    reason: [
      ["src","Source: HM Land Registry Price Paid Data and the EPC register, joined by exact address within full postcode, 13 August 2026; Data Room 3.4.1 Savills pp. 5, 24 and 51; European cohort research pack, 6 August 2026. Land Registry prices the whole title, so farm and estate titles are never blended into a distribution."],
    ] }}
  ]
}},'''


# ══ chapter 06 ════════════════════════════════════════════════════════
def ch06():
    def cs(field, fmt=m1):
        return [fmt(CASE[k][field]) for k in ("base", "keys_45", "trophy_downside")]

    irrs = [f"{CASE[k]['irr']*100:.2f}%" for k in ("base", "keys_45")]
    tro = CASE["trophy_downside"]
    tro_irr = neg(tro["irr"])
    ems = [f"{CASE[k]['em']:.2f}x" for k in ("base", "keys_45", "trophy_downside")]
    unlev = [f"{CASE[k]['irr_unlev']*100:.2f}%" for k in ("base", "keys_45", "trophy_downside")]
    rev = cs("y7_rev", m2)
    gopm = [f"{CASE[k]['y7_gop']/CASE[k]['y7_rev']*100:.2f}%"
            for k in ("base", "keys_45", "trophy_downside")]
    cto, peak, teq, exv, resi = (cs("cost_to_open"), cs("peak_equity"), cs("total_equity"),
                                 cs("exit_price"), cs("resi_net"))
    prof = cs("profit")
    prof[2] = f"<span class='neg'>({m1(abs(tro['profit']))})</span>" if tro["profit"] < 0 else prof[2]
    return f'''{{
  id: "returns", num: "06", eyebrow: "Returns", title: "Returns &amp; the Entry Ladder",
  blurb: "The three cases, the exit evidence, every rung of the entry ladder and the single-lever sensitivities.",
  figures: [["{F['irr']} / {F['em']}","At the ruled {F['entry']}"],["{BS['0.13']['fig']}","Where 13.00% solves"]],
  views: [
  {{ id: "", title: "Returns &amp; the Entry Ladder", kicker: "Returns",
    figure: "{F['irr']} / {F['em']} at {F['entry']}", blurb: "",
    lead: [
      ["kpis",[["{F['irr']}","Levered IRR at the ruled price"],["{F['em']}","Equity multiple"],["{F['peak_equity']}","Peak equity"],["{F['levered_profit']}","Levered profit"]]],
      ["ladder"],
    ],
    reason: [
      ["para","Every rung is measured on the model at that entry. The rule marks the 13.00% bar; the lever columns show the level one input alone must reach to hold it."],
      ["src", LADDER.src],
    ] }},
  {{ id: "cases", title: "The Cases", kicker: "Cases",
    figure: "{F['irr']} against a downside of {tro_irr}", blurb: "The case, a scope case and a downside, measured side by side.",
    lead: [
      ["tbl",{{"cls":"num wide","head":["Measure, at the ruled price",{{"t":"The case","a":"r"}},{{"t":"45-key scope case","a":"r"}},{{"t":"Trophy downside","a":"r"}}],"rows":[
        ["key",["Levered IRR","<span class='emph'>{F['irr']}</span>","{irrs[1]}","<span class='neg'>{tro_irr}</span>"]],
        ["key",["Equity multiple","<span class='emph'>{F['em']}</span>","{ems[1]}","{ems[2]}"]],
        [null,["Unlevered IRR","{unlev[0]}","{unlev[1]}","{unlev[2]}"]],
        [null,["Year-7 revenue","{rev[0]}","{rev[1]}","{rev[2]}"]],
        [null,["Year-7 GOP margin","{gopm[0]}","{gopm[1]}","{gopm[2]}"]],
        [null,["Cost to open","{cto[0]}","{cto[1]}","{cto[2]}"]],
        [null,["Peak equity","{peak[0]}","{peak[1]}","{peak[2]}"]],
        [null,["Equity drawn in total","{teq[0]}","{teq[1]}","{teq[2]}"]],
        [null,["Exit value","{exv[0]}","{exv[1]}","{exv[2]}"]],
        [null,["Residences, net","{resi[0]}","{resi[1]}","{resi[2]}"]],
        ["total",["Levered profit","<span class='emph'>{prof[0]}</span>","{prof[1]}","{prof[2]}"]]],"note":"<b>What each column is.</b> <b>45-key scope case</b>: the same book with the key count set to 45. It costs more than a key count usually would, because the capital cost is a schedule of buildings and estate rather than a price a key: fifteen fewer keys take the revenue away and leave the budget where it was. No consented 45-key scheme is evidenced in the data room. <b>Trophy downside</b>: the same book re-cut at a \u00a3750 rate, an occupancy override reaching 0.55, residences at \u00a3850 a square foot, an exit at 4.375%, the buyouts and corporate events halved and Regatta covers at 200 a day."}}],
    ],
    reason: [
      ["src","Source: Align model, {MODEL_NAME} \u2014 the case, the same book at 45 keys, and the trophy-downside recipe, each measured at the ruled {F['entry']} price on {SAVED}. Multiples are struck on equity drawn. Two older columns are not shown: a floor case built on Financial Model v12 and a flag-failure branch, both of which carry an earlier fee stack and an earlier capital cost, and neither of which can be reproduced on this version. They printed 6.56% and (31.20)% on their own books, and they are lineage references rather than cases of this underwrite."],
    ] }},
  {{ id: "sensitivities", title: "Single-Lever Sensitivities", kicker: "Sensitivity",
    figure: "The club the largest lever, {D['swings']['club']}", blurb: "One dial at a time at the ruled price, measured on the model.",
    lead: [
      ["tbl",{{"cls":"num wide","head":["Dial",{{"t":"Weaker","a":"r"}},{{"t":"Underwritten","a":"r"}},{{"t":"Stronger","a":"r"}},"Swing and note"],"rows":[
        [null,["ADR, year 1","\u00a3850 {ARROW} {p2('adr_850')}","<span class='emph'>{F['adr_y1']} {ARROW} {F['irr']}</span>","\u00a31,200 {ARROW} {p2('adr_1200')}","{D['swings']['adr']} across the band. The four operator forecasts average \u00a31,183 at their own stabilised year"]],
        [null,["Exit yield","4.75% {ARROW} {p2('exit_475')}","<span class='emph'>{F['exit_yield']} {ARROW} {F['irr']}</span>","3.50% {ARROW} {p2('exit_350')}","{D['swings']['exit_yield']}. Every non-London trade held prints 5.42\u20136.00%"]],
        [null,["Staff cost index","1.30 {ARROW} {p2('staff_130')}","<span class='emph'>{F['staff_index']} {ARROW} {F['irr']}</span>","1.00 {ARROW} {p2('staff_100')}","{D['swings']['staff']}. The margin frame runs it against the evidence"]],
        [null,["Occupancy, stabilised","0.60 {ARROW} {p2('occ_060')}","<span class='emph'>{F['occ_stab']} {ARROW} {F['irr']}</span>","0.70 {ARROW} {p2('occ_070')}","{D['swings']['occupancy']}. The narrative interval is 60\u201370%; the four operator forecasts average 65.5%, and 0.67 returns {p2('occ_067')}"]],
        [null,["The members\u2019 club","Off {ARROW} {p2('club_off')}","<span class='emph'>{F['members']} at {F['member_fee']} {ARROW} {F['irr']}</span>","{MDASH}","{D['swings']['club']}, the largest single lever in the model. At \u00a3490 a month it returns {p2('club_490')}. No filed comparable exists for the fee"]],
        [null,["Keys","45 {ARROW} {p2('keys_45')}","<span class='emph'>60 {ARROW} {F['irr']}</span>","{MDASH}","{abs(S['keys_45']['d_pp']):.1f}pp. The capital cost is a schedule of buildings and estate, so fifteen fewer keys take the revenue and leave the budget"]],
        [null,["Exclusive-use buyouts","Off {ARROW} {p2('buyouts_off')}","<span class='emph'>{F['buyouts_y7']} at {F['buyout_premium']} {ARROW} {F['irr']}</span>","{MDASH}","{abs(S['buyouts_off']['d_pp']):.1f}pp. The premium has no filed comparable either"]],
        [null,["Residences \u00a3/sqft","\u00a31,100 {ARROW} {p2('resi_1100')}","<span class='emph'>{F['resi_psf']} {ARROW} {F['irr']}</span>","\u00a31,500 {ARROW} {p2('resi_1500')}","{D['swings']['resi_psf']}. Twelve units at {F['resi_sqft']} sqft; \u00a3100/sqft is \u00a36.6m of gross before escalation"]],
        [null,["Residential price growth","0% {ARROW} {p2('resi_esc_0')}","<span class='emph'>{F['resi_esc']} {ARROW} {F['irr']}</span>","{MDASH}","{D['swings']['resi_growth']} between nil and the 2.5% general inflation rate; the model runs {F['resi_esc']}, above it"]],
        [null,["Regatta","Off {ARROW} {p2('regatta_off')}","<span class='emph'>{F['regatta_days']} days {ARROW} {F['irr']}</span>","{MDASH}","{D['swings']['regatta']}, on the vendor\u2019s own six-day format"]],
        [null,["Courtyard keys","{MDASH}","<span class='emph'>12 {ARROW} {F['irr']}</span>","43 {ARROW} {p2('courtyard_43')}","{D['swings']['courtyard']}. The consented courtyard count is 15; 24 keys returns {p2('courtyard_24')}"]],
        [null,["Works programme","18 quarters {ARROW} {p2('programme_18')}","<span class='emph'>{F['capex_prog_q']} quarters {ARROW} {F['irr']}</span>","{MDASH}","A longer programme costs a little: 16 quarters returns {p2('programme_16')}, because the schedule spends against its own dates"]],
        [null,["Financing","SONIA 4.5% {ARROW} {p2('sonia_45')}","<span class='emph'>{F['base_rate']} {ARROW} {F['irr']}</span>","{MDASH}","The refinancing is sized on a {F['refi_min_icr']} cover test; at 1.30x it returns {p2('icr_130')} and at 1.40x {p2('icr_140')}"]],
        [null,["Operator incentive","8% {ARROW} {p2('incentive_8')}","<span class='emph'>{F['fee_incentive']} {ARROW} {F['irr']}</span>","{MDASH}","{D['swings']['incentive']}. Subordinating the incentive rather than cutting it is the chip the HMA negotiation still holds"]]],"note":"The exit is modelled as a sale of the holding company\u2019s shares, on which no corporate gain arises in the vehicle. Selling the asset instead, at {F['tax_corp']} on the gain, returns {p2('asset_sale')} \u2014 {X['asset_sale']['d_pp']}pp against the case \u2014 and pays {X['asset_sale']['cgt']} of capital gains tax on the {X['asset_sale']['gain']} gain, on top of the {X['base_tax']} of corporation tax the hold pays either way. It is the largest structuring exposure in the underwrite. Two further exposures are named rather than measured here: the lender cash-trap the model does not carry, and construction escalation, both of which the model review prices."}}],
    ],
    reason: [
      ["para","Each row moves one dial at the ruled {F['entry']} price and holds everything else. The IRR is measured on the model at every setting shown, on scratch copies, with the state restored and the baseline re-verified after each one."],
      ["src","Source: Align model, {MODEL_NAME}, measured on scratch copies {SAVED} by substitution, with every reported setting read back through the model and the baseline re-verified at {F['irr_4dp']} afterwards. The occupancy rows move the stabilised plateau and its ramp year together and leave the construction years alone. The scheme rows move the twelve switches on the capital schedule, each of which carries its own cost and revenue. The tax row moves the capital-gains rate from nil to {F['tax_corp']} and reads the corporation-tax and capital-gains rows of the cash flow."],
    ] }},
  {{ id: "exit", title: "Exit Yield &amp; Value per Key", kicker: "Exit",
    figure: "{F['exit_yield']} \u00b7 {F['exit_per_key']} a key", blurb: "Every country-house, resort and trophy trade held with a published price.",
    lead: [
      ["tbl",{{"cls":"num wide","head":["Evidence",{{"t":"Date","a":"c"}},{{"t":"Keys","a":"r"}},{{"t":"Per key","a":"r"}},{{"t":"Yield","a":"r"}},"Basis"],"rows":[
        ["subject",["Fawley Court {MDASH} exit","~T+8","60","<span class='emph'>{F['exit_per_key']}</span>","<span class='emph'>{F['exit_yield']}</span>","{F['exit_value']} hotel alone, on adjusted NOI of {F['exit_adjnoi']} over the gross-of-costs value"]],
        [null,["Six Senses London","2024","109","\u00a31.65m","{MDASH}","The flag\u2019s London debut, urban; no yield published"]],
        [null,["The Mere Golf Resort","2022","81","\u00a3424k","6.00%","Cheshire resort; 7.0% at its own 2018 trade"]],
        [null,["Fonab Castle","2022","43","\u00a3302k","{MDASH}","Perthshire castle hotel; no yield published"]],
        [null,["Stoke Park","2021","49","\u00a31.16m","5.42%","Country house bought for refurbishment closure; the closest trade held"]],
        [null,["The Ritz London","Mar 2020","136","\u00a35.15m","2.38%","\u00a3700m over 136 keys; a London transaction, not operationally comparable"]],
        [null,["Formby Hall","2020","76","\u00a3316k","5.80%","Golf resort, Merseyside"]],
        [null,["Rusacks St Andrews","2019","70","\u00a3643k","{MDASH}","St Andrews links-front; no yield published"]],
        [null,["Gleneagles","2015","232","\u00a3647k","5.50%","A 232-key UK resort transaction"]],
        [null,["Cliveden House","2012","41","\u00a3756k","{MDASH}","Country house, prior cycle; 41 keys at the trade, 47 today"]],
        [null,["UK hotels, index print","Q1 2025","{MDASH}","{MDASH}","4.50%","A published index level for UK hotels, not a transaction"]]],"note":"Four of the nine trades carry no published yield. Every country-house and resort trade here that does prints between 5.42% and 6.00%, and the only sub-3% yield is the London transaction at \u00a35.15m a key. The underwritten {F['exit_yield']} sits beyond that record on the yield, and {F['exit_per_key']} a key is above every trade held except that one. No trade held supports either level, and the gap widened with this version: the exit value rose with the capital cost while the evidence did not move."}}],
    ],
    reason: [
      ["src","Source: the transaction database, 426 UK trades of which 96 carry a published yield; shown are the country-house, resort and trophy trades with a published price. Colliers market index for the Q1 2025 print, an index level and not a trade. Align model for the subject. Transaction yields are as published at each trade and are not restated to a common basis; the subject is struck on adjusted NOI, after the operator and asset-management fees, over the gross-of-costs value."],
    ] }}
  ]
}},'''


# ══ chapter 07 ════════════════════════════════════════════════════════
def ch07():
    B = REC["bridge"]
    return f'''{{
  id: "bridge", num: "07", eyebrow: "The Bridge", title: "The IRR Bridge",
  blurb: "From the Embassy base case to the Align underwrite, one engine, seven measured levers.",
  figures: [["{B[0]['irr']} {ARROW} {B[7]['irr']}","Embassy base case to the Align underwrite"],["{REC['bridge_meta']['net_pp']}pp","Across seven levers"]],
  views: [
  {{ id: "", title: "The IRR Bridge", kicker: "Bridge",
    figure: "{B[0]['irr']} {ARROW} {B[7]['irr']}", blurb: "",
    lead: [
      ["bridge"],
    ],
    reason: [
    ] }}
  ]
}},'''


# ══ named replacements in the chapters that keep their shape ══════════
def replacements():
    return [
        # chapter 02 — the counterparty view's return figure
        ("12.99% and 1.84x", f"{F['irr']} and {F['em']}", None),
        # chapter 03 — the underwrite read against the comparables
        ("<span class='emph'>£45.33m</span>", f"<span class='emph'>{F['rev_y7']}</span>", None),
        ("<span class='emph'>£15.39m = 33.96% GOP</span>",
         f"<span class='emph'>{F['gop_y7']} = {F['gop_margin_y7']} GOP</span>", None),
        ("The underwritten 33.96% sits", f"The underwritten {F['gop_margin_y7']} sits", None),
        ('figure: "£2.06m a key"', f'figure: "{F["capex_hotel_per_key"]} a key"', None),
        ("<span class='emph'>£2.06m</span>", f"<span class='emph'>{F['capex_hotel_per_key']}</span>", None),
        ("£123.6m from a 146-line ground-up budget: quantity × rate a line, then 20% preliminaries, 12.5% fees and 15% contingency",
         f"{F['capex_hotel']} from a 162-line ground-up budget: quantity × rate a line, then "
         f"{F['capex_prelims_pct']} preliminaries, {F['capex_fees_pct']} fees and "
         f"{F['capex_cont_pct']} contingency", None),
        ('figure: "33.96% GOP, sixth of eleven"',
         f'figure: "{F["gop_margin_y7"]} GOP, sixth of eleven"', None),
    ]


# ══ splice ════════════════════════════════════════════════════════════
def chapter_span(s, cid):
    """The whole chapter object, from its opening brace to the next one."""
    i = s.index(f'  id: "{cid}", num: "')
    start = s.rindex("{", 0, i)
    nxt = s.find('  id: "', i + 10)
    while nxt != -1 and s[nxt:nxt + 40].split('"')[1] in ("", cid):
        nxt = s.find('  id: "', nxt + 10)
    end = s.rindex("{", 0, nxt) if nxt != -1 else s.index("\n];", i)
    return start, end


def main():
    s = open(IDX, encoding="utf-8").read()
    before = len(s)

    for cid, text in (("summary", CH01), ("underwrite", ch04()), ("returns", ch06()),
                      ("bridge", ch07())):
        a, b = chapter_span(s, cid)
        s = s[:a] + text + "\n" + s[b:]
        print(f"  chapter {cid} rewritten")

    for old, new, want in replacements():
        n = s.count(old)
        assert n and (want is None or n == want), f"{n} hits for: {old[:70]}"
        s = s.replace(old, new)
        print(f"  x{n}  {old[:58]}")

    # the case plates read the underwrite against each comparable
    ca, cb = s.index("const CASES = ["), s.index("const CHEAT = {")
    seg = s[ca:cb]
    for old, new in (("33.96%", F["gop_margin_y7"]), ("£45.33m", F["rev_y7"]),
                     ("£123.6m", F["capex_hotel"]), ("£2.06m", F["capex_hotel_per_key"]),
                     ("£15.39m", F["gop_y7"])):
        n = seg.count(old)
        if n:
            seg = seg.replace(old, new)
            print(f"  cases x{n}  {old}")
    s = s[:ca] + seg + s[cb:]

    open(IDX, "w", encoding="utf-8", newline="").write(s)
    print(f"rewrote {IDX}  ({before:,} -> {len(s):,} bytes)")


if __name__ == "__main__":
    main()
